### ISSUE TITLE
Productionise our bot

### ISSUE THREAD

**Issue by robinj** [referendum-bot/fb-bot#1]
Before we can do anything more, we need to think of all of the use cases [here](https://github.com/referendum-bot/fb-bot/blob/master/docs/usecases.md) and then record a screencast which demos each use case. Please discuss any use cases that you think are needed here. Or fork this repo and put a pull request in (so we all get a chance to review it)
- [ ] use cases
- [ ] screencast 

Once we have done the above we will be allowed to publish to fb 
- [ ] submit to fb for approval

**Comment by cartolouis** [comment]
Additional use cases:
- Allow users to check their eligibility and find out how to register to vote
- Allow users to request a reminder to register to vote
